Test project
denisdiaconu/Newsweek-clone pull request #1
Opened 2021-01-25 15:56 UTC by denisdiaconu

finished the navbar and the footer of the page for phone, desktop, tablet size.

2021-01-25 17:28 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.

- [ ] on the footer, the copyright text should be exactly next to the logo, without the extra space  ([Link to page](https://www.newsweek.com/))
- [ ] place add the gray area on the sides of the page ([Link to page](https://www.newsweek.com/))
- [ ] the text of the nav links are going above the red background, that shouldn't happen.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  display: flex;
- [ ] Use Bootstrap for Display Flex.

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  align-items: flex-end;
- [ ] you can use `align-items-end` as a class.

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  display: flex;
- [ ]  Use Bootstrap for Display Flex.

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  justify-content: space-between;
- [ ]  Use Bootstrap for Display Flex.
- [ ]  Use Bootstrap for aligning Items.
- [ ] Use Bootstrap for justifying content.

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  align-items: center;
- [ ]  Use Bootstrap for Display Flex.
- [ ]  Use Bootstrap for aligning Items.

2021-01-25 17:28 UTC, Spayco commented on style.css
> +  display: none;
- [ ] use `d-none` for `display: none;`

2021-01-25 17:28 UTC, Spayco commented on style.css
> +    display: none;
- [ ] use `d-none` for `display: none;`

2021-01-25 17:28 UTC, Spayco commented on style.css
> +    justify-content: flex-end;
- [ ] you can use `align-items-end` as a class.

2021-01-26 15:54 UTC, denisdiaconu commented
Added col 1, col 2, col 3 and their layout

2021-01-26 19:39 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.

- [x]  on the third column, I don't see the **Free signup** section
- [x] The content order and disposition changes to the correct place in tablet and mobile
- [x] Use bootstrap classes instead of using your custom CSS file as much as possible, I mentioned some below 👇, but double-check if I missed some.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  align-items: center;
- [ ] use `align-items-center` Bootstrap class for this.

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  display: none;
- [ ] use `d-none` Bootstrap class for this, also, don't mark these as an ID because you might use it for multiple elements.

2021-01-26 19:39 UTC, Spayco commented on style.css
> +  display: flex;
- [ ] use `d-flex` for this.

2021-01-26 19:39 UTC, Spayco commented on style.css
> +    font-weight: bold;
- [ ] Use `font-weight-bold` Bootstrap class for this

2021-01-26 19:39 UTC, Spayco commented on style.css
> +    display: inline;
- [ ] use `d-inline` Bootstrap class for this.

2021-01-27 15:40 UTC, denisdiaconu commented
> # Milestone Approved heavy_check_mark
> 
> Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.
> 
>     * [ ]   on the third column, I don't see the **Free signup** section
> 
>     * [ ]  The content order and disposition changes to the correct place in tablet and mobile
> 
>     * [ ]  Use bootstrap classes instead of using your custom CSS file as much as possible, I mentioned some below point_down, but double-check if I missed some.
> 
> 
> ### please don't forget to merge to master, good luck with the next projects!
> 
> Best,
> Aziz Mejri
> _contact me on [twitter](https://twitter.com/iSpaYco) or slack (@Spayco) if you need any help_

Thank you for the review!
I will fix them until tomorrow.

2021-01-27 15:42 UTC, denisdiaconu commented
Added the last part of the page.

    US
    World
    Business
    Tech & Science
    Culture
    Sports
    Expert forum

2021-01-28 02:03 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)
### Hello @denisdiaconu :balloon: 

### Thank you for your submission :handshake: your project looks very similar to the original and a few changes need to be made at this point, claps for the good work done so far :clap: :clap: :clap: let's work on the following changes :construction_worker: 

### General

- [x] Readme file has some spelling mistakes, and broken screenshots let's fix them
- [ ] Use [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp)
> each picture with its heading should be surrounded by an article tag also make use of the aside tag for the sections below the editor's picks.
- [x] NOT make [common mistakes](https://speckyboy.com/good-bad-css-practices) in your CSS styles
> I found inline styling in several lines of your HTML file please, use only bootstrap classes for styling, and only if this is not possible create your own classes for styles but all the styles should be put in the CSS file.

### Implementation requirements

* [ ] Use Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options))

> The previous reviewer put comments directly in the CSS file, but I'll also put them here you should use bootstrap classes and the CSS file should be as small as possible so let's use bootstrap classes for the following selectors:
- margin: (0, auto)
- padding: (0, auto)
- list-style: none
- width: auto
- height: auto
- text-decoration: none;
- align-items: (all that applies)
- color: (black, white, red)
- display: (all that applies)
- font-weight: (all that applies)
- flex-direction: (all that applies)
- justify-content: (all that applies)
- position: (all that applies)
- font-size: (al that applies)
- align-content: (all that applies)

### All Milestone requirements

#### Mobile Screens
##### Navbar
- [x] The login, SUBSCRIBE button, and hamburger menu needs some margin between each other **also do it for tablet screens**
- Clone
![image](https://user-images.githubusercontent.com/52209067/106059676-a8f7e780-60b8-11eb-8d91-82bf4aa9ccab.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106059708-b4e3a980-60b8-11eb-9efd-c9f43364376f.png)
- [x] The Navbar is overlapping or being overlapped by some sections make sure it has the higher z-index
- Clone
![image](https://user-images.githubusercontent.com/52209067/106068232-e020c580-60c5-11eb-8f1a-0ba1a3c0cf18.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106068278-f62e8600-60c5-11eb-83ae-02a10194a2cb.png)
##### TOP STORY to MY TURN
- [x] all the articles should have more margin on the left
- Clone
![image](https://user-images.githubusercontent.com/52209067/106066524-984c6f00-60c2-11eb-99d0-78ee347e19a2.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106066592-b4501080-60c2-11eb-8368-00d25029b9c8.png)
##### Sign up form
- [ ] should be smaller in width 
- Clone
![image](https://user-images.githubusercontent.com/52209067/106068633-78b74580-60c6-11eb-9782-56ca369db67c.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106068672-88cf2500-60c6-11eb-9ed7-78fc60ef6eda.png)
##### IN THE MAGAZINE
- [ ] The Section heading is not showing and the Issue magazine should be larger in height
- Clone
![image](https://user-images.githubusercontent.com/52209067/106068943-19a60080-60c7-11eb-92b1-1addcb7ca979.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106069049-5e319c00-60c7-11eb-8ac4-d9e7a057cd6d.png)
##### Main news sections (U.S., World, etc.)
- [ ] The images of the small articles should take 60% of the screen width and the text should have a margin on the left to separate it from the image **The margin applies for all screen sizes**
- Clone
![image](https://user-images.githubusercontent.com/52209067/106070023-4ce98f00-60c9-11eb-98be-95edc59b1da1.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106070063-5c68d800-60c9-11eb-86d6-e61d0d58740d.png)

##### SUBSCRIBE
- [ ] The images, text and subscribe button should be centered and the bold text should be on top of the images
- Clone
![image](https://user-images.githubusercontent.com/52209067/106070294-ced9b800-60c9-11eb-8c24-c83fb46839fd.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106070333-e31db500-60c9-11eb-8ef9-210903ab4d0a.png)

##### NEWSLEETTER
- [ ] The image should be on top and take the whole section width and half of the section height, the text should be centered, and the email input field next to the FREE SIGN UP button
- Clone
![image](https://user-images.githubusercontent.com/52209067/106072816-7eb12480-60ce-11eb-86e5-af94796af95f.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106072842-8a9ce680-60ce-11eb-8fd0-dacf10a73207.png)

#### Tablet Screens
##### Column 1 and 2
- [ ] The headings for these columns aren't showing, or are being covered by the navbar so let's give some margin on top to correct this on this screens size
- Clone
![image](https://user-images.githubusercontent.com/52209067/106060259-6551ad80-60b9-11eb-9eb8-0c23e034d045.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106060310-77cbe700-60b9-11eb-9699-915ac5d17728.png)
##### Culture & Travel and More Stories
these sections should have more separation between each other the text of the articles its almost on top of the Section headings
- Clone
![image](https://user-images.githubusercontent.com/52209067/106073410-a359cc00-60cf-11eb-8fcf-c770c607c8da.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106073450-b53b6f00-60cf-11eb-81d7-b0e955de44f5.png)
##### Sponsored Insight / Rankins and the FREE SIGN UP form
- [ ] should be smaller and  center on the page
Clone
![image](https://user-images.githubusercontent.com/52209067/106073670-21b66e00-60d0-11eb-8b62-11a5ddbfe0ea.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106073721-372b9800-60d0-11eb-9fff-58b0572f2837.png)
##### Editor's Picks
the images should be larger in height
Clone
![image](https://user-images.githubusercontent.com/52209067/106076056-70660700-60d4-11eb-89dc-d06ba2afed22.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106076088-7d82f600-60d4-11eb-935e-531cbf7cf428.png)
##### SUBSCRIBE 
- [ ] The red heading should have a smaller font size, the text and subscribe button should have a margin on the left to separate them from the overlapping images
- Clone
![image](https://user-images.githubusercontent.com/52209067/106076731-c4bdb680-60d5-11eb-8288-1ec67cfde8b0.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106076765-d43cff80-60d5-11eb-8725-6c1b8482cec7.png)
##### NEWSLETTER

- [ ] The red heading should have a smaller font size, the image should be along with the section heading, there's a gray border on the right part containing the text, the text is centered in the right part and the Email address input is next to the FREE SIGN UP button
Clone
![image](https://user-images.githubusercontent.com/52209067/106077296-e9fef480-60d6-11eb-97eb-a3137b98e8cd.png)
Original
![image](https://user-images.githubusercontent.com/52209067/106077333-f8e5a700-60d6-11eb-9f32-9f27530e29ed.png)

#### Desktop Screens
##### Navbar
- [ ] The date and SUBSCRIBE buttons are on the edge of the screen let's add some margin
![image](https://user-images.githubusercontent.com/52209067/106059003-a648c280-60b7-11eb-923d-84a6c99f99e2.png)
- [ ] The Navbar should be centered in the page like the following sections so let's also add some margin 
- Clone
![image](https://user-images.githubusercontent.com/52209067/106059316-27a05500-60b8-11eb-98de-0bc23a7c2ae1.png)
- Original
![image](https://user-images.githubusercontent.com/52209067/106059379-4272c980-60b8-11eb-8a0 [...]

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                <button type="button" class="btn btn-warning button" style="border-radius: 23px; font-weight: bold; color: black; height: 30px; background-color: #ffe400;">SUBSCRIBE ></button>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                <li style="border: none;"><a href="#">U.S.</a></li>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                    <p style="color: #b7b7b7; margin: auto;">Search</p>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                <li id="border_red" style="height: 100%;"></li>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                <li style="font-weight: bold;"><span>TREDING</span></li>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                <button class="btn btn-sm" type="button" style="font-size: 12px; height: 25px; border-radius: 24px; background-color: #ffe400;"><strong>SUBSCRIBE ></strong></button>
- [x] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                    <div style="background-color: #f4f5f6;" class="px-3 py-4 border rounded first_form">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                            <a href="#" class="h4" style="background-color: #f72210; padding: 5px 9px 5px 9px; font-weight: bold; color: white;">N</a>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                            <button type="button" style="background-color: #f61602;" class="col-12 rounded bg-red px-6 py-1 mt-3 ">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                    <section class="bg-white col-12 magazin_cont" style="padding-top: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                            <div class="d-flex justify-content-center" style="background-color: #f4f5f6;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <section class="bg-white border-bottom col-12 editor_cont" style="padding-top: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                        <section style="padding-top: 40px;" class="row bg-white col-12">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                                        <button class="btn font-weight-bold btn-danger" style="background-color: red;">SUBSCRIBE</button>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                                    <div class="d-flex col-12" style="height: 90%;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex" style="column-gap: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                  <div style="background-color: #f4f5f6;" class="px-3 py-4 border rounded first_form">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <a href="#" class="h4" style="background-color: #f72210; padding: 5px 9px 5px 9px; font-weight: bold; color: white;">N</a>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <button type="button" style="background-color: #f61602;" class="col-12 rounded bg-red px-6 py-1 mt-3 ">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +              <h3 style="padding: 5px; font-size: 20px; font-weight: bold;">IN THE MAGAZINE</h3>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +            <section class="bg-white magazin_cont" style="padding-top: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                  <div class="d-flex justify-content-center" style="background-color: #f4f5f6;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                  <h3 style="padding: 5px; font-size: 20px; font-weight: bold;">EDITOR'S PICKS</h3>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +              <section class="bg-white border-bottom col-12 editor_cont" style="padding-top: 20px;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +              <section style="padding-top: 40px;" class="row bg-white col-12">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                              <button class="btn font-weight-bold btn-danger" style="background-color: red;">SUBSCRIBE</button>
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +                          <div class="d-flex col-12" style="height: 90%;">
- [ ] Use bootstrap classes when possible or put all styles within your own classes in the CSS file

2021-01-28 02:03 UTC, euqueme commented on index.html
> +    <title>Title</title>
- [x] Use a meaningful name like "NEWSWEEK CLONE" instead of using Title

2021-01-28 14:35 UTC, denisdiaconu commented
Thanks for the review!

Fix:

- The copyright text in the footer is next to the logo.
- Added gray area on the sides of the page
- The text of the nav links isn't above the red background now.
- Added the **Free signup** section.
- The content of the page changes to the correct place now for tablet, mobile, and desktop.
- Fixed spelling mistakes inside README and repaired the screenshot.
- Changed div with semantic HTML.
- Repaired inline styling.
- Used Bootstrap CSS on every single element.
- Added margin between the items of the phone & tablet navbar.
- Added tighter z-index so navbar is overlapping.
- Added margin to the left to all the articles.
-  The signup form is smaller in width now.
- The section heading of the magazine section is showing now.
- Fixed the size of the images on the small articles.
- The images, text and subscribe button inside the subscribe section are centered now.
- The images, text, and **Free sign up** button of the newsletter section are centered now.
- The headings of the columns are showing now.
- **My turn and Culture & Travel** have more space between each other now.
- The sponsored part of the page is now smaller and centered
- The images of the Editor's pick section are now higher.
- The read heading of the subscribe and Newsletter section is now smaller.
- Added some margin to the date and subscribe buttons.
- Added margin between articles.
- The images of the sponsored and ranking section are showing now.
- Fixed the font size of some articles.
- Added margin to the footer.
- Made all the images into links.

Thank you for the review.

2021-01-28 17:12 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] your subscribe section is breaking on mobile.
- [ ] fix the previous notes about CSS properties that can be Bootstrap classes.

![image](https://user-images.githubusercontent.com/11758151/106173443-36f4d080-6194-11eb-9fb7-e215030a80c5.png)


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-28 18:52 UTC, denisdiaconu commented
I talked with the last code reviewer and he told me that the subscribe section is ok.
Is normal for the text to be inside the images.
I did my best and I changed everything that could be changed in bootstrap.
Only a few remain but they are in big groups.
Thank you for the review!

2021-01-29 01:20 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-29 07:02 UTC, merged